#!/usr/bin/env python3
"""
Network-accessible backend startup script
Auto-generated by get-local-ip.js
"""

import uvicorn
from app.main import app

if __name__ == "__main__":
    print("🚀 Starting Safe Wave Backend on network...")
    print(f"📱 Local Network URL: http://192.168.31.14:9000")
    print(f"📚 API Documentation: http://192.168.31.14:9000/docs")
    print(f"🏥 Health Check: http://192.168.31.14:9000/health")
    print(f"📊 API Info: http://192.168.31.14:9000/info")
    print("")
    print("🔗 Use this URL in your mobile app to connect from other devices")
    print("📱 Make sure your mobile device is on the same WiFi network")
    print("")

    uvicorn.run(
        "app.main:app",
        host="192.168.31.14",
        port=9000,
        reload=True,
        log_level="info"
    )
