services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: safe-wave-backend:dev
    env_file:
      - .env
    command: bash -lc "until pg_isready -h db -p 5432 -U ${POSTGRES_USER} -q; do echo 'waiting for db'; sleep 1; done; export PGPASSWORD=${POSTGRES_PASSWORD}; DB_NAME=${POSTGRES_DB:-safewave}; psql -h db -p 5432 -U ${POSTGRES_USER} -tc \"SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'\" | grep -q 1 || psql -h db -p 5432 -U ${POSTGRES_USER} -c \"CREATE DATABASE \\\"${DB_NAME}\\\"\"; unset PGPASSWORD; poetry run alembic upgrade head && poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - backend-uploads:/app/uploads
      - ./models:/app/models
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app} -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    restart: unless-stopped

volumes:
  db-data:
  backend-uploads:
