"""Add audio analysis table

Revision ID: 002
Revises: 001
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(), nullable=False),
    sa.Column('audio_duration', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('transcription_confidence', sa.Integer(), nullable=True),
    sa.Column('llm_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('mental_health_indicators', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('care_person_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_analyses_id'), 'audio_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_audio_analyses_user_id'), 'audio_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_audio_analyses_user_id'), table_name='audio_analyses')
    op.drop_index(op.f('ix_audio_analyses_id'), table_name='audio_analyses')
    op.drop_table('audio_analyses')
    # ### end Alembic commands ###
